INHERIT: ./config/0_md_extensions.yml

# Project information
site_name: Geotribu Sandbox
site_description: >-
  Site indépendant de veille sur la géomatique libre et open source.
  Articles, tutoriels et revues de presse (#GeoRDP) sur
  l'information géographique, les SIG, la cartographie, la représentation des données...

site_author: Geotribu
site_url: https://static.geotribu.fr/
copyright: '<span class="copyleft">&copy;</span> Geotribu'

# Repository
repo_name: !ENV [GITHUB_REPOSITORY, "geotribu/website"]
repo_url: !ENV [MKDOCS_REPO_URL, "https://github.com/geotribu/website"]
edit_uri: !ENV [MKDOCS_EDIT_URI, "edit/master/content"]

# Custom folder structure
docs_dir: './content'
site_dir: './build/mkdocs/site'


# Theme
theme:
  name: 'material'
  custom_dir: './content/theme/'
  favicon: "https://cdn.geotribu.fr/img/internal/charte/geotribu_logo_64x64.png"

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  features:
    - content.tabs.link
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  font: false
  icon:
    repo: fontawesome/brands/github-alt
  language: 'fr'
  logo: "https://cdn.geotribu.fr/img/internal/charte/geotribu_logo_64x64.png"
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep-orange
      toggle:
        icon: material/weather-sunny
        name: Basculer en mode sombre

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: deep-orange
      toggle:
        icon: material/weather-night
        name: Basculer en mode clair

extra_css:
  - 'theme/assets/stylesheets/extra.css'
  # - 'theme/assets/stylesheets/homepage.css'
  - 'https://cdn.jsdelivr.net/npm/wa-mediabox@1.0.1/dist/wa-mediabox.min.css'

extra_javascript:
  - 'theme/assets/javascripts/extra.js'
  - 'https://cdn.jsdelivr.net/npm/wa-mediabox@1.0.1/dist/wa-mediabox.min.js'
