INHERIT: ./1_plugins.yml

# Extensions to enhance markdown - see: https://squidfunk.github.io/mkdocs-material/getting-started/#extensions
markdown_extensions:
  - abbr
  # Admonition - https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - admonition
  - attr_list
  # Footnotes - https://squidfunk.github.io/mkdocs-material/reference/footnotes/
  - footnotes
  # Metadata - https://squidfunk.github.io/mkdocs-material/extensions/metadata
  - meta
  # PyMdown extensions - https://squidfunk.github.io/mkdocs-material/extensions/pymdown/
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.saneheaders
  # https://facelessuser.github.io/pymdown-extensions/extensions/snippets/
  - pymdownx.snippets:
      auto_append: [content/toc_nav_ignored/snippets/glossaire.md]
      base_path: "."
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  # Permalinks - https://squidfunk.github.io/mkdocs-material/extensions/permalinks/
  - toc:
      permalink: "#"
