INHERIT: ./2_extra.yml

plugins:
  - awesome-pages
  - exclude:
      glob:
        - "*/templates/*"
        - "*.yml"
  - git-authors:
      enabled: !ENV [MKDOCS_ENABLE_PLUGIN_GIT_AUTHORS, False]
      exclude:
        - index.md
  - git-revision-date-localized:
      enabled: !ENV [MKDOCS_ENABLE_PLUGIN_GIT_DATES, False]
      enable_creation_date: true
      fallback_to_build_date: true
      locale: fr
  - minify:
      minify_css: true
      minify_html: true
      minify_js: false
      htmlmin_opts:
        remove_comments: true
  - rss:
      abstract_chars_count: 500
      categories:
        - categories
        - tags
      comments_path: "#__comments"
      date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%Y-%m-%d %H:%M"
      enabled: !ENV [MKDOCS_ENABLE_PLUGIN_RSS, false]
      image: "https://cdn.geotribu.fr/img/internal/charte/geotribu_logo_64x64.png"
      length: 50
      match_path: "(articles|rdp)/.*"
      pretty_print: true
      url_parameters:
        utm_source: "rss-feed"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"
  - search:
      lang: fr
  - macros:
      include_dir: content/toc_nav_ignored/snippets
  - redirects:
      redirect_maps:
        "acknowledgements.md": "team/index.md"
  - tags:
      tags_file: tags.md
