INHERIT: ./2_extra.yml

plugins:
  - awesome-pages
  - exclude:
      glob:
        - "*/templates/*"
        - "*.yml"
  - git-authors:
      enabled: !ENV [MKDOCS_ENABLE_PLUGIN_GIT_AUTHORS, False]
      exclude:
        - index.md
  - git-revision-date-localized:
      enabled: !ENV [MKDOCS_ENABLE_PLUGIN_GIT_DATES, False]
      enable_creation_date: true
      fallback_to_build_date: true
      locale: fr
  - minify:
      minify_css: true
      minify_html: true
      minify_js: false
      htmlmin_opts:
        remove_comments: true
  - rss:
      abstract_chars_count: 500
      categories:
        - categories
        - tags
      comments_path: "#__comments"
      date_from_meta:
        as_creation: "date"
        as_update: false
        datetime_format: "%Y-%m-%d %H:%M"
      enabled: !ENV [MKDOCS_ENABLE_PLUGIN_RSS, false]
      image: "https://cdn.geotribu.fr/img/internal/charte/geotribu_logo_64x64.png"
      length: 50
      match_path: "(articles|rdp)/.*"
      pretty_print: true
      url_parameters:
        utm_source: "rss-feed"
        utm_medium: "RSS"
        utm_campaign: "feed-syndication"
  - search:
      lang: fr
  - macros:
      include_dir: content/toc_nav_ignored/snippets
  - redirects:
      redirect_maps:
        # RSS
        "rss.md": "https://static.geotribu.fr/feed_rss_created.xml"
        # contenus
        "dicogis.md": "articles/2014/art_2014-09-25_dicogis.md"
        "GeoRDP/20161028.md": "rdp/2016/rdp_2016-10-14.md"
        "node/270.md": "articles/2010/art_2010-06-11.md"
        "node/348.md": "rdp/2011/rdp_2011-02-25.md"
        "node/423.md": "articles/2011/art_2011-06-15.md"
        "node/462.md": "articles/2011/art_2011-11-09.md"
        "node/488.md": "rdp/2012/rdp_2012-01-13.md"
        "node/520.md": "articles/2012/art_2012-06-21.md"
        "node/532.md": "articles/2012/art_2012-07-12.md"
        "node/636.md": "articles/2013/art_2013-09-26.md"
        # correction de la structure initiale de la résurrection
        "rdp/rdp_2020-04-30.md": "rdp/2020/rdp_2020-04-30.md"
        # geogames
        "node/668.md": "articles/2013/art_2013-10-30_geogame_mots_croises_outils_sig.md"
        "node/671.md": "https://geotribu.github.io/geogames/"
        "node/675.md": "articles/2013/art_2013-11-20_geogame_mots_croises_webmapping.md"
        "node/679.md": "articles/2014/art_2014-01-08_geogame_qcm_histoire_cartographie.md"
        "node/689.md": "articles/2014/art_2014-01-22_geogame_qcm_cassini_bertin.md"
        "node/680.md": "articles/2014/art_2014-03-19_geogame_pendu_geomatique.md"
        # recent moves
        "acknowledgements.md": "team/index.md"
        "install_webapp.md": "articles/2020/2020-03-20_installer_site_comme_application.md"
  - tags:
      tags_file: tags.md
