
# Customization
extra:
  comments_url: http://localhost:8080  # isso url
  social:
    - icon: 'fontawesome/solid/rss'
      link: 'https://static.geotribu.fr/feed_rss_created.xml'
      name: "S'abonner aux nouveaux contenus via RSS"
    - icon: 'fontawesome/brands/github-alt'
      link: 'https://github.com/geotribu/'
      name: "L'organisation Github de Geotribu"
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/geotribu'
      name: "Geotribu sur Twitter"
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/feed/hashtag/?keywords=geotribu'
      name: "Les contenus de Geotribu sur LinkedIn"
    - icon: 'fontawesome/brands/facebook'
      link: 'https://fr-fr.facebook.com/geotribu/'
      name: "Page Facebook de Geotribu"
    - icon: fontawesome/solid/paper-plane
      link: mailto:<geotribu@gmail.com>
      name: "Nous contacter"
    - icon: 'fontawesome/brands/slack'
      link: 'https://geotribu.slack.com'
      name: "Rejoignez-nous sur Slack"
