# Trigger
on:
  pull_request:
    branches: [main]
    paths:
      - "content/**/*.md"

jobs:
  lilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14

      - uses: xt0rted/markdownlint-problem-matcher@v1

      - run: markdownlint -i "**/template_*.md" -i node_modules content/**/*.md
