name: reporter

# Trigger
on:
  pull_request:
    branches: [main]
    paths:
      - "content/**/*.md"

jobs:
  mdlint-report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: markdownlint-github-check
        uses: reviewdog/action-markdownlint@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          level: warning
          filter_mode: nofilter

      - name: markdownlint
        uses: reviewdog/action-markdownlint@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          markdownlint_flags: --config=.markdownlint.json content/
