name: reporter

# Trigger
on:
  pull_request:
    branches: [main]
    paths:
      - "content/**/*.md"

jobs:
  mdlint-report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: markdownlint
        uses: reviewdog/action-markdownlint@v0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
          # filter_mode: diff
          markdownlint_flags: "--config .markdownlint.json --ignore **/template_*.md content/**/*.md"
