name: reporter

# Trigger
on:
  pull_request:
    branches: [main]
    paths:
      - "content/**/*.md"

jobs:
  mdlint-report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: markdownlint-github-pr-review
        uses: reviewdog/action-markdownlint@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
          filter_mode: diff_context
          reporter: github-pr-review
          markdownlint_flags: content/**/*.md
